# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vitree < Formula
  desc "Tiny Go TUI that browses the current directory and forwards files to vim"
  homepage "https://github.com/hoffa/vitree"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hoffa/vitree/releases/download/v0.4.1/vitree_0.4.1_darwin_amd64.tar.gz"
      sha256 "f7ef6b7788749aa3ee092ae28c6fd3bc26b845b11571e7417ad0db8c8531ff37"

      define_method(:install) do
        bin.install "vitree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hoffa/vitree/releases/download/v0.4.1/vitree_0.4.1_darwin_arm64.tar.gz"
      sha256 "3ee8bec66d78d6814e5ae043aefdface38d8c35773be9c2e3320ca57b46f5639"

      define_method(:install) do
        bin.install "vitree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoffa/vitree/releases/download/v0.4.1/vitree_0.4.1_linux_amd64.tar.gz"
      sha256 "9660ff13dbdcc18ca0adfa636b08e8ee6557d4adc4227e07a0db8c8fcf335ede"
      define_method(:install) do
        bin.install "vitree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoffa/vitree/releases/download/v0.4.1/vitree_0.4.1_linux_arm64.tar.gz"
      sha256 "ee0102ab5b63e1435347747127e98a521978c0dae567bb492a5f6fcadb70001d"
      define_method(:install) do
        bin.install "vitree"
      end
    end
  end

  test do
    system "#{bin}/vitree", "-version"
  end
end
