# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vitree < Formula
  desc "Tiny Go TUI that browses the current directory and forwards files to vim"
  homepage "https://github.com/hoffa/vitree"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hoffa/vitree/releases/download/v0.4.3/vitree_0.4.3_darwin_amd64.tar.gz"
      sha256 "ecf4a7b40014f3b9ab48a095eb2d7cd0fdc39d12ffe8c4c630a6b28251b4dab7"

      define_method(:install) do
        bin.install "vitree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hoffa/vitree/releases/download/v0.4.3/vitree_0.4.3_darwin_arm64.tar.gz"
      sha256 "cd1bc02eda01da78e64c2660f38a48b56660238f85ce796e37ba381c16c6d997"

      define_method(:install) do
        bin.install "vitree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoffa/vitree/releases/download/v0.4.3/vitree_0.4.3_linux_amd64.tar.gz"
      sha256 "2fe975393e5ddc052b5a0d91e8a71df51da1ab20063e6d295ec5ef5faad50cf3"
      define_method(:install) do
        bin.install "vitree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoffa/vitree/releases/download/v0.4.3/vitree_0.4.3_linux_arm64.tar.gz"
      sha256 "e3ee10f18c28750691d910e4de6575f0dfdf65b43fc2ff4eefbc86214e0bb479"
      define_method(:install) do
        bin.install "vitree"
      end
    end
  end

  test do
    system "#{bin}/vitree", "-version"
  end
end
