# This file was generated by GoReleaser. DO NOT EDIT.
cask "bk" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "c817b05a9f0447ad9943a56aba5656b02ee907bfb00977dfb49630fe3f6d9233"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
    on_arm do
      sha256 "ad1ade8adae7edf36f77b93e3be10c6eaac400ac124544a7ee1bcb98419e6dad"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d7836bc29abcb11870159f28f293d19c2a6a596dd484645ce3b2d1e1bfb32dd"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
    on_arm do
      sha256 "b3fd68ee7b4a9721065dd56f2b3b0a32a7cca0367a6e1d38717b9c4aa8bb03af"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
  end

  name "bk"
  desc "Versioned git repository backups using append-only bundles"
  homepage "https://github.com/hoffa/bk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bk"]
    end
  end

  # No zap stanza required

end
