# This file was generated by GoReleaser. DO NOT EDIT.
cask "bk" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "06986eeae9a87fcac6de951ab85d509514c9a7266fd8013a99e9f1c855368e66"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
    on_arm do
      sha256 "50c30357d185ce34db5b8b90b5005ac4aa044e92eac3343ca9c4bb9c038a3b73"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2216c8051532d775df136027f2fcce9fe7b8b3bdf64bfd4682ac24a6037b705"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
    on_arm do
      sha256 "67045a419e6f86d5fa05c7f1e1caa16450e8b0c0c0db89c0689e970151f89fe6"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
  end

  name "bk"
  desc "Versioned git repository backups using append-only bundles"
  homepage "https://github.com/hoffa/bk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bk"]
    end
  end

  # No zap stanza required

end
