# This file was generated by GoReleaser. DO NOT EDIT.
cask "bk" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "a6640f5057875c7135a70835625315798ff124fca0346bb93590c47a221648ad"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
    on_arm do
      sha256 "8bb2807cfbfe0d7373c5706649dc194ace394dfb94c07d26a59fdb60438bac0d"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1fabef92355e5314b2b186ab2fc6fdc78edd6c3f2ccddece90a9e74a383c932"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
    on_arm do
      sha256 "3b6cd0b550df4b2db8081f4d61092e8427a05319f12b8899264966c4c3d6a63f"
      url "https://github.com/hoffa/bk/releases/download/v#{version}/bk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hoffa/bk"
    end
  end

  name "bk"
  desc "Versioned git repository backups using append-only bundles"
  homepage "https://github.com/hoffa/bk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bk"]
    end
  end

  # No zap stanza required

end
