# This file was generated by GoReleaser. DO NOT EDIT.
cask "vitree" do
  version "0.5.3"

  on_macos do
    on_intel do
      sha256 "3e8284aebaf07214c5bcb3d287ce2b7570afbfc8d9475d640260b7bc443e0645"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hoffa/vitree"
    end
    on_arm do
      sha256 "84e51dd10bd407f6fef8771e542ffe7240d99ca44fc9de4a45c21e521e1f0edb"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hoffa/vitree"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b2544768f9bb061106562dbc5ae71bdfcd6cb383a2cfad63045f08daa3a15b4"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hoffa/vitree"
    end
    on_arm do
      sha256 "362651ce19b559ad95751d706b0a35dd40acdcd26dbac8c9b4815abf7ef6c285"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hoffa/vitree"
    end
  end

  name "vitree"
  desc "A Vim file browser running in a separate terminal"
  homepage "https://github.com/hoffa/vitree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vitree"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vitree"]
    end
  end

  # No zap stanza required

end
