# This file was generated by GoReleaser. DO NOT EDIT.
cask "vitree" do
  version "0.4.6"

  on_macos do
    on_intel do
      sha256 "428a87d3c6725653f835e238362c29beeffc50d92a69ff4fb8e60635ca05bcd8"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9dc47847c9a571d75bc6790835adb38d26fe7851972b802aa83b102f4f678e8"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "afa744e886b39d23acf29470d29c239f6a39000f32605822e66fe8d5ec8f3097"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0d9d9056d4e004f599e521d47f0055776b8dc0c9fe81b2b39f9ced954349581"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vitree"
  desc "Tiny Go TUI that browses the current directory and forwards files to vim"
  homepage "https://github.com/hoffa/vitree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vitree"

  # No zap stanza required

end
