# This file was generated by GoReleaser. DO NOT EDIT.
cask "vitree" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "c176012ca56d5ce088c2a688ce67964caddeeb3c74093d92384fde333f798eb5"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hoffa/vitree"
    end
    on_arm do
      sha256 "4a4a0aee6463873bc91082c1205fa98152b4ba85164152e77b33727ef7680f1a"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hoffa/vitree"
    end
  end

  on_linux do
    on_intel do
      sha256 "43b8254554f17ca216198beb929eb12bf437369b5a52082590fc715c22e18350"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hoffa/vitree"
    end
    on_arm do
      sha256 "0d408ecb3550b169493ba6a54d4bd299acdc9c7a52083f6e994fed1cf55a641c"
      url "https://github.com/hoffa/vitree/releases/download/v#{version}/vitree_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hoffa/vitree"
    end
  end

  name "vitree"
  desc "A Vim file browser running in a separate terminal"
  homepage "https://github.com/hoffa/vitree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vitree"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vitree"]
    end
  end

  # No zap stanza required

end
